# Generated by Django 4.1.5 on 2023-01-18 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_child', to=settings.AUTH_USER_MODEL)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='main.children')),
            ],
        ),
    ]
