# Generated by Django 4.1.4 on 2023-01-24 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritePets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_pets', to=settings.AUTH_USER_MODEL)),
                ('pets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_pets', to='main.pets')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteNarsingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_narsing_house', to=settings.AUTH_USER_MODEL)),
                ('narsing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_narsing_house', to='main.narsinghouse')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteHomeless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_homeless', to=settings.AUTH_USER_MODEL)),
                ('homeless', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_homeless', to='main.homeless')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteChildrenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_children_house', to=settings.AUTH_USER_MODEL)),
                ('children_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_chidldren_house', to='main.childrenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteChildren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_children', to=settings.AUTH_USER_MODEL)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_children', to='main.children')),
            ],
        ),
    ]
