# Generated by Django 4.1.5 on 2023-01-18 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FavouritePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_pets', to=settings.AUTH_USER_MODEL)),
                ('pets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='main.pets')),
            ],
        ),
    ]
