# Generated by Django 4.1.5 on 2023-01-18 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_alter_favourite_author_favouritepet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_children', to=settings.AUTH_USER_MODEL)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_child', to='main.children')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteChildH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_chs', to=settings.AUTH_USER_MODEL)),
                ('childho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_ch', to='main.children_house')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteHom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_Homelessts', to=settings.AUTH_USER_MODEL)),
                ('hmless', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_homeless', to='main.homeless')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteNrsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_nrhs', to=settings.AUTH_USER_MODEL)),
                ('nrshouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_nrh', to='main.narsing_house')),
            ],
        ),
        migrations.AlterField(
            model_name='favouritepet',
            name='pets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_pet', to='main.pets'),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
