# Generated by Django 4.1.5 on 2023-01-18 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_favouritechild_favouritechildh_favouritehom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritehom',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_homelessts', to=settings.AUTH_USER_MODEL),
        ),
    ]
