# Generated by Django 4.1.5 on 2023-01-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_favouritehom_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritehom',
            old_name='hmless',
            new_name='homeless',
        ),
    ]
