# Generated by Django 4.1.5 on 2023-01-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_rename_hmless_favouritehom_homeless'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritechildh',
            old_name='childho',
            new_name='child_house',
        ),
        migrations.RenameField(
            model_name='favouritenrsh',
            old_name='nrshouse',
            new_name='narsing_house',
        ),
    ]
