# Generated by Django 4.1.5 on 2023-01-18 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0006_rename_childho_favouritechildh_child_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritechild',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favouritechildh',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_childh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favouritehom',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_hom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favouritenrsh',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_nrh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favouritepet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_pet', to=settings.AUTH_USER_MODEL),
        ),
    ]
